#DATA CLEANSING PADA DATA PEMEGANG SAHAM DI ATAS 1% PER 31 JULI 2026
Dataset yang digunakan merupakan data pemegang saham di atas 1% per 31 Juli 2026 yang diperoleh dari situs resmi Bursa Efek Indonesia (BEI)

Tujuan:

Untuk memperbaiki data yang tidak konsisten, menangani data yang kosong, serta menghapus data yang duplikat agar dataset menjadi lebih rapi dan siap digunakan untuk analisis

##1.Persiapan Data
Pada Tahap ini dilakukan untuk menyiapkan Google Colab dan dataset sebelum masuk ke proses data cleansing

###1.1 Mount Google Drive

Google Drive digunakan untuk mengakses file dataset yang telah disimpan pada penyimpanan GoogleDrive

In [1]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

###1.2 Import Library
Library yang digunakan untuk membantu proses membaca, mengolah, dan membersihkan dataset

In [14]:
import pandas as pd
import numpy as np
import re

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

###1.3 Import Dataset
Dataset kemudian dimuat ke dalam Google Colab menggunakan library Pandas agar dapat dilakukan pemeriksaan dan proses data cleansing

In [16]:
file_path = '/content/drive/MyDrive/Colab Notebooks/data_pemegang_saham_1persen_31juli2026.xlsx'

df = pd.read_excel(file_path)

df.head()

,DATE,SHARE_CODE,ISSUER_NAME,INVESTOR_NAME,INVESTOR_CLASSIFICATION,LOCAL_FOREIGN,NATIONALITY,DOMICILE,HOLDINGS_SCRIPLESS,HOLDINGS_SCRIP,TOTAL_HOLDING_SHARES,PERCENTAGE
0,2026-07-31 00:00:00,LMAS,LIMAS INDONESIA MAKMUR Tbk,widayanti darmawan,individual,L,INDONESIAN,INDONESIA,12448000,0,12448000,1.58
1,2026-07-31,TPIA,Chandra Asri Pacific Tbk,Bangkok Bank Public Company Limited,Bank,F,NaN,THAILAND,4317648400,0,4317648400,4.99
2,2026-07-31 00:00:00,VAST,Vastland Indonesia Tbk,ARI ANASTASIA CHRISTIANA,Individual,l,INDONESIAN,INDONESIA,39659000,0,"39,659,000",1.3
3,2026-07-31 00:00:00,TKIM,PABRIK KERTAS TJIWI KIMIA Tbk,BOQUETE GROUP S.A.,NaN,F,NaN,NaN,0,83852816,"83,852,816","2,69%"
4,31-Jul-2026,MMIX,Multi Medika Internasional Tbk,EVELINE NATALIA SUSANTO,Individual,L,INDONESIAN,INDONESIA,288000000,0,288000000,"6,0"

## 2.Pemeriksaan Awal Dataset
Pada tahap ini dilakukan pemeriksaan awal untuk mengetahui kondisi dataset sebelum proses cleansing, seperti jumlah data, nama kolom, dan tipe data

###2.1 Informasi Dataset
Pemeriksaan dilakukan untuk mengetahui jumlah baris, jumlah kolom, nama kolom, dan tipe data pada dataset

In [17]:
print("Jumlah baris  :", df.shape[0])
print("Jumlah kolom :", df.shape[1])

print("\nNama kolom:")
print(df.columns.tolist())

print("\nTipe data:")
print(df.dtypes)

Jumlah baris  : 50
Jumlah kolom : 12

Nama kolom:
['DATE', 'SHARE_CODE', 'ISSUER_NAME', 'INVESTOR_NAME', 'INVESTOR_CLASSIFICATION', 'LOCAL_FOREIGN', 'NATIONALITY', 'DOMICILE', 'HOLDINGS_SCRIPLESS', 'HOLDINGS_SCRIP', 'TOTAL_HOLDING_SHARES', 'PERCENTAGE']

Tipe data:
DATE                       object
SHARE_CODE                 object
ISSUER_NAME                object
INVESTOR_NAME              object
INVESTOR_CLASSIFICATION    object
LOCAL_FOREIGN              object
NATIONALITY                object
DOMICILE                   object
HOLDINGS_SCRIPLESS         object
HOLDINGS_SCRIP             object
TOTAL_HOLDING_SHARES       object
PERCENTAGE                 object
dtype: object

###2.2 Pemeriksaan Missing Value

Tahap ini dilakukan pemeriksaan untuk mengetahui apakah terdapat data yang kosong pada setiap kolom. Hasil pemeriksaan ini akan menjadi dasar untuk menentukan penanganan missing value pada tahap cleansing

In [19]:
missing_value = df.isna().sum()

print("Jumlah missing value pada setiap kolom:")
print(missing_value)

Jumlah missing value pada setiap kolom:
DATE                        0
SHARE_CODE                  0
ISSUER_NAME                 0
INVESTOR_NAME               0
INVESTOR_CLASSIFICATION     4
LOCAL_FOREIGN               3
NATIONALITY                39
DOMICILE                   10
HOLDINGS_SCRIPLESS          0
HOLDINGS_SCRIP              0
TOTAL_HOLDING_SHARES        0
PERCENTAGE                  0
dtype: int64

###2.3 Pemeriksaan Data Duplikat

Selanjutnya tahap ini dilakukan pemeriksaan terhadap data yang memiliki nilai yang sama untuk mengetahui apakah terdapat data duplikat sebelum proses cleansing

In [23]:
duplicate_count = df[df.duplicated()].sum()


print("Jumlah data duplikat:", duplicate_count)

Jumlah data duplikat: DATE                       0
SHARE_CODE                 0
ISSUER_NAME                0
INVESTOR_NAME              0
INVESTOR_CLASSIFICATION    0
LOCAL_FOREIGN              0
NATIONALITY                0
DOMICILE                   0
HOLDINGS_SCRIPLESS         0
HOLDINGS_SCRIP             0
TOTAL_HOLDING_SHARES       0
PERCENTAGE                 0
dtype: object

##3.Data Cleansing – Standarisasi
Lalu Tahap ini dilakukan standarisasi untuk menyamakan format data yang masih memiliki perbedaan penulisan. Tujuannya agar data menjadi lebih konsisten dan mudah digunakan untuk proses analisis

###3.1 Standarisasi SHARE_CODE

Kode saham seharusnya memiliki format yang konsisten. Pada tahap ini  membersihkan spasi dan menyamakan huruf menjadi huruf kapita

In [24]:
df['SHARE_CODE'] = (
    df['SHARE_CODE']
    .astype('string')
    .str.strip()
    .str.upper()
)

df[['SHARE_CODE']].head()

  SHARE_CODE
0       LMAS
1       TPIA
2       VAST
3       TKIM
4       MMIX

###3.2 Standarisasi ISSUER_NAME

Kolom ISSUER_NAME dibersihkan dengan menghapus spasi berlebih dan menyamakan format penulisan menjadi huruf kapital

In [25]:
df['ISSUER_NAME'] = (
    df['ISSUER_NAME']
    .astype('string')
    .str.strip()
    .str.upper()
)

df[['ISSUER_NAME']].head()

                      ISSUER_NAME
0      LIMAS INDONESIA MAKMUR TBK
1        CHANDRA ASRI PACIFIC TBK
2          VASTLAND INDONESIA TBK
3   PABRIK KERTAS TJIWI KIMIA TBK
4  MULTI MEDIKA INTERNASIONAL TBK

###3.3 Standarisasi INVESTOR_NAME

Kolom INVESTOR_NAME dibersihkan dengan menghapus spasi yang tidak diperlukan dan menyamakan penulisan menjadi huruf kapital

In [26]:
df['INVESTOR_NAME'] = (
    df['INVESTOR_NAME']
    .astype('string')
    .str.strip()
    .str.upper()
)

df[['INVESTOR_NAME']].head()

                          INVESTOR_NAME
0                    WIDAYANTI DARMAWAN
1  BANGKOK  BANK PUBLIC COMPANY LIMITED
2              ARI ANASTASIA CHRISTIANA
3                    BOQUETE GROUP S.A.
4               EVELINE NATALIA SUSANTO

In [66]:
df['INVESTOR_CLASSIFICATION'] = (
    df['INVESTOR_CLASSIFICATION']
    .astype('string')
    .str.strip()
    .str.upper()
)

df[['INVESTOR_CLASSIFICATION']].head()

  INVESTOR_CLASSIFICATION
0              INDIVIDUAL
1                    BANK
2              INDIVIDUAL
3                 UNKNOWN
4              INDIVIDUAL

###3.4 Standarisasi INVESTOR_CLASSIFICATION
Pada kolom INVESTOR_CLASSIFICATION, dilakukan standarisasi dengan menghilangkan spasi berlebih dan mengubah seluruh huruf menjadi huruf kapital agar format data menjadi konsisten.

###3.5 Standarisasi DATE

Standarisasi tanggal dilakukan agar format tanggal menjadi seragam dan lebih mudah digunakan dalam analisis

In [27]:
df['DATE'] = pd.to_datetime(
    df['DATE'],
    errors='coerce',
    dayfirst=True
)

df['DATE'] = df['DATE'].dt.strftime('%Y-%m-%d')

df[['DATE']].head()

         DATE
0  2026-07-31
1  2026-07-31
2  2026-07-31
3  2026-07-31
4  2026-07-31

###3.6 Standarisasi LOCAL_FOREIGN

Kolom LOCAL_FOREIGN distandarisasi dengan menghapus spasi yang tidak diperlukan dan menyamakan penulisan menjadi huruf kapital

In [54]:
# Membersihkan spasi dan menyamakan huruf
df['LOCAL_FOREIGN'] = (
    df['LOCAL_FOREIGN']
    .astype('string')
    .str.strip()
    .str.upper()
)

# Menyamakan kode L/F dengan LOCAL/FOREIGN
df['LOCAL_FOREIGN'] = df['LOCAL_FOREIGN'].replace({
    'L': 'LOCAL',
    'F': 'FOREIGN'
})

df[['LOCAL_FOREIGN']].value_counts()

LOCAL_FOREIGN
LOCAL            31
FOREIGN          16
UNKNOWN           3
Name: count, dtype: int64

###3.7 Standarisasi Data Numerik

Kolom jumlah kepemilikan saham dikonversi menjadi tipe data numerik, Karakter pemisah angka yang tidak diperlukan akan dibersihkan sebelum data dikonversi

In [101]:
numeric_columns = [
    'HOLDINGS_SCRIPLESS',
    'HOLDINGS_SCRIP',
    'TOTAL_HOLDING_SHARES'
]

for col in numeric_columns:
    df[col] = (
        df[col]
        .astype('string')
        .str.replace(',', '', regex=False)
        .str.replace('.', '', regex=False)
        .str.strip()
    )

    df[col] = pd.to_numeric(
        df[col],
        errors='coerce'
    )

display(
    df[numeric_columns].style.format('{:,.0f}')
)

###3.8 Standarisasi PERCENTAGE

Kolom PERCENTAGE dibersihkan dari simbol persen dan disesuaikan format desimalnya, kemudian dikonversi menjadi tipe data numerik

In [102]:
df['PERCENTAGE'] = (
    df['PERCENTAGE']
    .astype('string')
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip()
)

df['PERCENTAGE'] = pd.to_numeric(
    df['PERCENTAGE'],
    errors='coerce'
)

df[['PERCENTAGE']].head()

   PERCENTAGE
0        1.58
1        4.99
2         1.3
3        2.69
4         6.0

## 4.Data Cleansing – Missing Value
Tahap ini dilakukan penanganan terhadap data yang kosong. Data kosong diperiksa terlebih dahulu, kemudian diberikan nilai yang sesuai agar dataset dapat digunakan untuk analisi

###4.1 Identifikasi Missing Value

In [74]:
missing_value = df.isna().sum()

print("Jumlah missing value:")
print(missing_value)

Jumlah missing value:
DATE                       0
SHARE_CODE                 0
ISSUER_NAME                0
INVESTOR_NAME              0
INVESTOR_CLASSIFICATION    0
LOCAL_FOREIGN              0
NATIONALITY                0
DOMICILE                   0
HOLDINGS_SCRIPLESS         0
HOLDINGS_SCRIP             0
TOTAL_HOLDING_SHARES       0
PERCENTAGE                 0
INVESTOR_TYPE              0
dtype: int64

###4.2 Penanganan Missing Value

Untuk data kategorikal yang kosong, gunakan nilai Unknown karena nilai sebenarnya tidak diketahui. agar tidak mengarang nilai yang seharusnya

In [75]:
categorical_columns = [
    'INVESTOR_CLASSIFICATION',
    'LOCAL_FOREIGN',
    'NATIONALITY',
    'DOMICILE'
]

for col in categorical_columns:
    df[col] = df[col].fillna('Unknown')

print("Missing value setelah penanganan:")
print(df.isna().sum())

Missing value setelah penanganan:
DATE                       0
SHARE_CODE                 0
ISSUER_NAME                0
INVESTOR_NAME              0
INVESTOR_CLASSIFICATION    0
LOCAL_FOREIGN              0
NATIONALITY                0
DOMICILE                   0
HOLDINGS_SCRIPLESS         0
HOLDINGS_SCRIP             0
TOTAL_HOLDING_SHARES       0
PERCENTAGE                 0
INVESTOR_TYPE              0
dtype: int64

## 5.Data Cleansing – Deduplikasi
Data duplikat perlu diperiksa karena keberadaan data yang sama dapat memengaruhi hasil analisis

###5.1 Identifikasi Data Duplikat

In [76]:
duplicate_count = df.duplicated().sum()

print("Jumlah data duplikat:", duplicate_count)

Jumlah data duplikat: 0

## 6.Data Enrichment
Pada tahap ini dilakukan penambahan informasi berdasarkan data yang tersedia melalui tabel referensi (lookup), Informasi tambahan digunakan untuk membuat data lebih mudah dipahami

###6.1 Membuat Data Lookup

In [77]:
lookup_investor = pd.DataFrame({
    'LOCAL_FOREIGN': ['LOCAL', 'FOREIGN', 'UNKNOWN'],
    'INVESTOR_TYPE': [
        'Investor Lokal',
        'Investor Asing',
        'Tidak Diketahui'
    ]
})

lookup_investor

  LOCAL_FOREIGN    INVESTOR_TYPE
0         LOCAL   Investor Lokal
1       FOREIGN   Investor Asing
2       UNKNOWN  Tidak Diketahui

###6.2 Menggabungkan Data Lookup

Sebelum melakukan merge, pastikan nilai LOCAL_FOREIGN yang kosong sudah menjadi Unknown dan disesuaikan dengan lookup

In [104]:
df['LOCAL_FOREIGN'] = (
    df['LOCAL_FOREIGN']
    .fillna('UNKNOWN')
    .astype('string')
    .str.strip()
    .str.upper()
)

df['LOCAL_FOREIGN'] = df['LOCAL_FOREIGN'].replace({
    'L': 'LOCAL',
    'F': 'FOREIGN'
})

In [105]:
df['INVESTOR_TYPE'] = df['INVESTOR_TYPE'].fillna('Tidak Diketahui')

df[['LOCAL_FOREIGN', 'INVESTOR_TYPE']].head(10)

  LOCAL_FOREIGN    INVESTOR_TYPE
0         LOCAL   Investor Lokal
1       FOREIGN   Investor Asing
2         LOCAL   Investor Lokal
3       FOREIGN   Investor Asing
4         LOCAL   Investor Lokal
5         LOCAL   Investor Lokal
6       UNKNOWN  Tidak Diketahui
7         LOCAL   Investor Lokal
8         LOCAL   Investor Lokal
9       FOREIGN   Investor Asing

In [103]:
print("Jumlah kolom setelah enrichment:", df.shape[1])

df.head()

Jumlah kolom setelah enrichment: 13

,DATE,SHARE_CODE,ISSUER_NAME,INVESTOR_NAME,INVESTOR_CLASSIFICATION,LOCAL_FOREIGN,NATIONALITY,DOMICILE,HOLDINGS_SCRIPLESS,HOLDINGS_SCRIP,TOTAL_HOLDING_SHARES,PERCENTAGE,INVESTOR_TYPE
0,2026-07-31,LMAS,LIMAS INDONESIA MAKMUR TBK,WIDAYANTI DARMAWAN,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,12448000,0,12448000,1.58,Investor Lokal
1,2026-07-31,TPIA,CHANDRA ASRI PACIFIC TBK,BANGKOK BANK PUBLIC COMPANY LIMITED,BANK,FOREIGN,Unknown,THAILAND,4317648400,0,4317648400,4.99,Investor Asing
2,2026-07-31,VAST,VASTLAND INDONESIA TBK,ARI ANASTASIA CHRISTIANA,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,39659000,0,39659000,1.3,Investor Lokal
3,2026-07-31,TKIM,PABRIK KERTAS TJIWI KIMIA TBK,BOQUETE GROUP S.A.,UNKNOWN,FOREIGN,Unknown,Unknown,0,83852816,83852816,2.69,Investor Asing
4,2026-07-31,MMIX,MULTI MEDIKA INTERNASIONAL TBK,EVELINE NATALIA SUSANTO,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,288000000,0,288000000,6.0,Investor Lokal

## 7.Pemeriksaan Dataset Setelah Cleansing
Setelah seluruh proses cleansing selesai, dilakukan pemeriksaan kembali untuk memastikan data sudah lebih rapi, tidak memiliki missing value yang tidak ditangani, dan tidak terdapat data duplikat

###7.1 Pemeriksaan Missing Value

In [67]:
print("Missing value setelah cleansing:")
print(df.isna().sum())

Missing value setelah cleansing:
DATE                       0
SHARE_CODE                 0
ISSUER_NAME                0
INVESTOR_NAME              0
INVESTOR_CLASSIFICATION    0
LOCAL_FOREIGN              0
NATIONALITY                0
DOMICILE                   0
HOLDINGS_SCRIPLESS         0
HOLDINGS_SCRIP             0
TOTAL_HOLDING_SHARES       0
PERCENTAGE                 0
INVESTOR_TYPE              0
dtype: int64

###7.2 Pemeriksaan Data Duplikat

In [106]:
print("Jumlah data duplikat setelah cleansing:")

print(
    df.duplicated(
        subset=['DATE', 'SHARE_CODE', 'INVESTOR_NAME']
    ).sum()
)

Jumlah data duplikat setelah cleansing:
0

###7.3 Pemeriksaan Hasil Akhir

Pada tahap ini ditampilkan kembali ukuran dataset, tipe data, dan beberapa baris data untuk melihat hasil akhir setelah proses cleansing

In [69]:
print("Jumlah baris  :", df.shape[0])
print("Jumlah kolom :", df.shape[1])

print("\nTipe data:")
print(df.dtypes)

print("\n5 data pertama:")
display(df.head())

Jumlah baris  : 50
Jumlah kolom : 13

Tipe data:
DATE                               object
SHARE_CODE                 string[python]
ISSUER_NAME                string[python]
INVESTOR_NAME              string[python]
INVESTOR_CLASSIFICATION    string[python]
LOCAL_FOREIGN                      object
NATIONALITY                        object
DOMICILE                           object
HOLDINGS_SCRIPLESS                  Int64
HOLDINGS_SCRIP                      Int64
TOTAL_HOLDING_SHARES                Int64
PERCENTAGE                        Float64
INVESTOR_TYPE                      object
dtype: object

5 data pertama:

,DATE,SHARE_CODE,ISSUER_NAME,INVESTOR_NAME,INVESTOR_CLASSIFICATION,LOCAL_FOREIGN,NATIONALITY,DOMICILE,HOLDINGS_SCRIPLESS,HOLDINGS_SCRIP,TOTAL_HOLDING_SHARES,PERCENTAGE,INVESTOR_TYPE
0,2026-07-31,LMAS,LIMAS INDONESIA MAKMUR TBK,WIDAYANTI DARMAWAN,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,12448000,0,12448000,1.58,Investor Lokal
1,2026-07-31,TPIA,CHANDRA ASRI PACIFIC TBK,BANGKOK BANK PUBLIC COMPANY LIMITED,BANK,FOREIGN,Unknown,THAILAND,4317648400,0,4317648400,4.99,Investor Asing
2,2026-07-31,VAST,VASTLAND INDONESIA TBK,ARI ANASTASIA CHRISTIANA,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,39659000,0,39659000,1.3,Investor Lokal
3,2026-07-31,TKIM,PABRIK KERTAS TJIWI KIMIA TBK,BOQUETE GROUP S.A.,UNKNOWN,FOREIGN,Unknown,Unknown,0,83852816,83852816,2.69,Investor Asing
4,2026-07-31,MMIX,MULTI MEDIKA INTERNASIONAL TBK,EVELINE NATALIA SUSANTO,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,288000000,0,288000000,6.0,Investor Lokal

## 8.Export Dataset
Dataset hasil cleansing disimpan ke dalam folder Google Drive dengan nama file baru agar data asli tetap tersimpan

In [107]:
output_path = '/content/drive/MyDrive/Colab Notebooks/data_pemegang_saham_clean.xlsx'

df.to_excel(output_path, index=False)

print("Dataset berhasil disimpan di:")
print(output_path)

Dataset berhasil disimpan di:
/content/drive/MyDrive/Colab Notebooks/data_pemegang_saham_clean.xlsx

##Hasil Akhir

Berikut merupakan hasil dataset setelah seluruh proses data cleansing dilakukan.

In [108]:
display(df)

,DATE,SHARE_CODE,ISSUER_NAME,INVESTOR_NAME,INVESTOR_CLASSIFICATION,LOCAL_FOREIGN,NATIONALITY,DOMICILE,HOLDINGS_SCRIPLESS,HOLDINGS_SCRIP,TOTAL_HOLDING_SHARES,PERCENTAGE,INVESTOR_TYPE
0,2026-07-31,LMAS,LIMAS INDONESIA MAKMUR TBK,WIDAYANTI DARMAWAN,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,12448000,0,12448000,1.58,Investor Lokal
1,2026-07-31,TPIA,CHANDRA ASRI PACIFIC TBK,BANGKOK BANK PUBLIC COMPANY LIMITED,BANK,FOREIGN,Unknown,THAILAND,4317648400,0,4317648400,4.99,Investor Asing
2,2026-07-31,VAST,VASTLAND INDONESIA TBK,ARI ANASTASIA CHRISTIANA,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,39659000,0,39659000,1.3,Investor Lokal
3,2026-07-31,TKIM,PABRIK KERTAS TJIWI KIMIA TBK,BOQUETE GROUP S.A.,UNKNOWN,FOREIGN,Unknown,Unknown,0,83852816,83852816,2.69,Investor Asing
4,2026-07-31,MMIX,MULTI MEDIKA INTERNASIONAL TBK,EVELINE NATALIA SUSANTO,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,288000000,0,288000000,6.0,Investor Lokal
5,2026-07-31,BBLD,BUANA FINANCE TBK,PT. GRAHA SENTOSA PERSADA,CORPORATE,LOCAL,Unknown,Indonesia,53098593,0,53098593,3.23,Investor Lokal
6,2026-07-31,DLTA,DELTA DJAKARTA TBK,PEMERINTAH DAERAH DKI JAKARTA,UNKNOWN,UNKNOWN,Unknown,Unknown,0,210200700,210200700,26.25,Tidak Diketahui
7,2026-07-31,YPAS,YANAPRIMA HASTAPERSADA TBK,HENDRA GUNAWAN GO,INDIVIDUAL,LOCAL,INDONESIAN,Unknown,32818100,0,32818100,4.91,Investor Lokal
8,2026-07-31,JGLE,GRAHA ANDRASENTRA PROPERTINDO TBK,PT.BIOFUEL INDO SUMATRA,VENTURE CAPITAL,LOCAL,Unknown,INDONESIA,233270000,0,233270000,1.03,Investor Lokal
9,2026-07-31,NICK,CHARNIC CAPITAL TBK,BANK JULIUS BAER AND CO. LTD. HONG KONG,PRIVATE BANK,FOREIGN,Unknown,HONG KONG,31500000,0,31500000,4.84,Investor Asing
10,2026-07-31,IPCM,JASA ARMADA INDONESIA TBK,PT ASURANSI KERUGIAN JASA RAHARJA,STATE OWNED ENTERPRISES,LOCAL,Unknown,Indonesia,211447400,0,211447400,4.0,Investor Lokal
11,2026-07-31,MYTX,ASIA PACIFIC INVESTAMA TBK,INDAH JAYA INVESTAMA PT,INVESTMENT FUND SELLING AGENT,LOCAL,Unknown,INDONESIA,5662429162,0,5662429162,73.09,Investor Lokal
12,2026-07-31,POLY,ASIA PACIFIC FIBERS TBK,CHENGWY KARLAM,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,82954900,0,82954900,3.59,Investor Lokal
13,2026-07-31,SKRN,SUPERKRANE MITRA UTAMA TBK,PT. SUPERKRANE MITRA UTAMA TBK,CORPORATE,LOCAL,Unknown,INDONESIA,382000174,0,382000174,5.09,Investor Lokal
14,2026-07-31,VINS,VICTORIA INSURANCE TBK,PT BINTANG JAYA BARA SENTOSA,CORPORATE,LOCAL,Unknown,INDONESIA,39029700,0,39029700,2.51,Investor Lokal
15,2026-07-31,SMKL,SATYAMITRA KEMAS LESTARI TBK,PT. SATYAMITRA INVESTINDO PRATAMA,CORPORATE,LOCAL,Unknown,INDONESIA,116689300,2722500000,2839189300,83.06,Investor Lokal
16,2026-07-31,MEGA,BANK MEGA TBK,PT INDOLIFE PENSIONTAMA,INSURANCE,LOCAL,Unknown,INDONESIA,1148371842,0,1148371842,4.89,Investor Lokal
17,2026-07-31,SIMP,SALIM IVOMAS PRATAMA TBK,PT. MANDIRI INVESTAMA SEJATI,CORPORATE,LOCAL,Unknown,Unknown,0,163540000,163540000,1.06,Investor Lokal
18,2026-07-31,WBSA,BSA LOGISTICS INDONESIA TBK,TIGA BERUANG KALIFORNIA PTE. LTD,CORPORATE,FOREIGN,Unknown,Unknown,0,6853975000,6853975000,79.01,Investor Asing
19,2026-07-31,LPPF,MDS RETAILING TBK,"REKSA PUSPITA KARYA,PT",CORPORATE,LOCAL,Unknown,INDONESIA,100000000,0,100000000,4.49,Investor Lokal
20,2026-07-31,UNIT,CAHAYA PERMATA SEJAHTERA TBK,PT KURNIA SENTOSA MULIA,CORPORATE,LOCAL,Unknown,INDONESIA,0,3725000,3725000,4.94,Investor Lokal
21,2026-07-31,PPRE,PP PRESISI TBK,PT.PEMBANGUNAN PERUMAHAN(PERSERO) TBK,CORPORATE,LOCAL,Unknown,INDONESIA,0,7871480000,7871480000,76.99,Investor Lokal
22,2026-07-31,FOOD,SENTRA FOOD INDONESIA TBK,SUDIONO PUJO,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,13723300,0,13723300,2.11,Investor Lokal
23,2026-07-31,AYLS,AGRO YASA LESTARI TBK,CHIFAN GRANETTA,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,17753500,0,17753500,2.08,Investor Lokal
24,2026-07-31,MGRO,MAHKOTA GROUP TBK,PT. MAHKOTA GROUP,CORPORATE,LOCAL,Unknown,INDONESIA,63871300,0,63871300,1.8,Investor Lokal
25,2026-07-31,CLPI,COLORPAK INDONESIA TBK,TJIA TJOEN HOK,INDIVIDUAL,LOCAL,INDONESIAN,Unknown,6867700,0,6867700,2.24,Investor Lokal
26,2026-07-31,ETWA,ETERINDO WAHANATAMA TBK,WATERVALE WORLDWIDE INC (WWI),UNKNOWN,UNKNOWN,Unknown,Unknown,0,211353700,211353700,4.53,Tidak Diketahui
27,2026-07-31,SUGI,"SUGIH ENERGY TBK, PT",EFFIE AGUSTINA S,INDIVIDUAL,LOCAL,INDONESIAN,Unknown,428169038,0,428169038,1.73,Investor Lokal
28,2026-07-31,BEST,BEKASI FAJAR INDUSTRIAL ESTATE TBK,PT ARGO MANUNGGAL LAND DEVELOPMENT,CORPORATE,LOCAL,Unknown,INDONESIA,4643604400,0,4643604400,48.13,Investor Lokal
29,2026-07-31,RIMO,RIMO INTERNATIONAL LESTARI TBK,RETAIL DEVELOPMENT GROUP LIMITED,FIRM,FOREIGN,Unknown,CAYMAN ISLANDS,2251480000,0,2251480000,4.99,Investor Asing
30,2026-07-31,FWCT,WIJAYA CAHAYA TIMBER TBK,FIRST FORTUNA HOLDINGS PTE.LTD,CORPORATE,FOREIGN,Unknown,SINGAPORE,467265100,0,467265100,23.8,Investor Asing
31,2026-07-31,PBSA,PARAMITA BANGUN SARANA TBK,UOB KAY HIAN PTE LTD,SECURITIES COMPANY,FOREIGN,Unknown,SINGAPORE,81708200,0,81708200,2.72,Investor Asing
32,2026-07-31,SMBR,SEMEN BATURAJA (PERSERO) TBK,PT SEMEN INDONESIA (PERSERO) TBK,CORPORATE,LOCAL,Unknown,INDONESIA,0,7499999999,7499999999,75.51,Investor Lokal
33,2026-07-31,BDMN,BANK DANAMON INDONESIA TBK,"UBS AG, LONDON",BANK,FOREIGN,Unknown,switzerland,160603387,0,160603387,1.64,Investor Asing
34,2026-07-31,JTPE,JASUINDO TIGA PERKASA TBK,ISLAM SANTOSA,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,97759700,0,97759700,1.43,Investor Lokal
35,2026-07-31,MSIN,MNC DIGITAL ENTERTAINMENT TBK,SINGAPORE GOLD LIMITED,CORPORATE,FOREIGN,Unknown,"VIRGIN ISLANDS, BRITISH",915851876,0,915851876,1.51,Investor Asing
36,2026-07-31,EMTK,ELANG MAHKOTA TEKNOLOGI TBK,PT ADIKARSA SARANA,CORPORATE,LOCAL,Unknown,indonesia,8654560360,0,8654560360,14.09,Investor Lokal
37,2026-07-31,NRCA,NUSA RAYA CIPTA TBK,"SURYA SEMESTA INTERNUSA TBK, PT",CORPORATE,LOCAL,Unknown,indonesia,1596200300,0,1596200300,63.94,Investor Lokal
38,2026-07-31,TGUK,PLATINUM WAHAB NUSANTARA TBK,MADA AZHARI,INDIVIDUAL,LOCAL,INDONESIAN,INDONESIA,89500000,0,89500000,2.51,Investor Lokal
39,2026-07-31,ABBA,MAHAKA MEDIA TBK,PT.GRID ONE MEDIA,CORPORATE,LOCAL,Unknown,INDONESIA,43791628,0,43791628,1.11,Investor Lokal
40,2026-07-31,COIN,INDOKRIPTO KOIN SEMESTA TBK,"DUTA PERKASA TEKNOLOGI, PT",INVESTMENT ADVISORS,LOCAL,Unknown,INDONESIA,500000000,0,500000000,3.4,Investor Lokal
41,2026-07-31,DADA,DIAMOND CITRA PROPERTINDO TBK,UOB KAY HIAN PTE LTD,SECURITIES COMPANY,FOREIGN,Unknown,SINGAPORE,100000000,0,100000000,1.35,Investor Asing
42,2026-07-31,CINT,CHITOSE INTERNASIONAL TBK,PT TRISULA INTERNATIONAL TBK,CORPORATE,LOCAL,Unknown,INDONESIA,40724000,0,40724000,4.07,Investor Lokal
43,2026-07-31,ADMF,ADIRA DINAMIKA MULTI FINANCE TBK,MUFG BANK LTD,PRIVATE BANK,FOREIGN,Unknown,JAPAN,233747459,0,233747459,18.91,Investor Asing
44,2026-07-31,LABS,UBC MEDICAL INDONESIA TBK,SUMMER BEGINNING LIMITED,PRIVATE EQUITY,FOREIGN,Unknown,"VIRGIN ISLANDS, BRITISH",117646900,0,117646900,2.98,Investor Asing
45,2026-07-31,SULI,SLJ GLOBAL TBK,NATUREVERSE INC. (PTE. LTD.),CORPORATE,FOREIGN,Unknown,SINGAPORE,2269423302,0,2269423302,35.9,Investor Asing
46,2026-07-31,SUPA,SUPER BANK INDONESIA TBK,KAKAOBANK CORP,BANK,FOREIGN,Unknown,"Korea, Republic Of",2934040535,0,2934040535,8.66,Investor Asing
47,2026-07-31,KICI,KEDAUNG INDAH CAN TBK,ASHLEY GROUP LIMITED,CORPORATE,FOREIGN,Unknown,Unknown,3328000,0,3328000,1.21,Investor Asing
48,2026-07-31,BBSI,KROM BANK INDONESIA TBK,HSBC LTD-SINGAPORE BRANCH PRIVATE BANKING DIV...,PRIVATE BANK,FOREIGN,Unknown,SINGAPORE,168135751,0,168135751,4.58,Investor Asing
49,2026-07-31,SCCO,SUPREME CABLE MANUFACTURING & COMMERCE TBK,"SUMBER DAYA SINAR BARU, PT",UNKNOWN,UNKNOWN,Unknown,Unknown,0,20216000,20216000,2.46,Tidak Diketahui